[theme]
font="sans-serif"
primaryColor="#ee7d3a" # Changed to a vibrant red for demonstration
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f5f4"
textColor="#374151"
baseRadius="medium"
linkColor="#344756"
linkUnderline=true # Added linkUnderline

# Basic Color Palette
redColor="#991b1b"
orangeColor="#ffa500"
yellowColor="#ffd700"
greenColor="#a8c655"
blueColor="#4a83c0"
violetColor="#cf539b"
grayColor="#9ca3af"
